<!doctype html><html lang=en><head><title>Solucionando problemas de sincronismo de requisições em paralelo com SemaphoreSlim :: Jojo's Exceptions</title><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><meta name=description content="Dando um push() no problema Um dos desafios que nem com as técnicas mais sombrias de debugging me ajudaram a entender o que meu contexto de requisições HTTP assíncronos e paralelos estavam retornando uma exceção baseada no cancelamento das referências das instâncias dos vários CancellationToken utilizados para construir o cliente das requisições.
Foi uma discussão bem legal com alguns monstros da CLR e até mesmo do Roslyn, que com uma paciência de Jó, conseguiram ir a fundo na explicação sobre o funcionamento da pilha de rede dentro do ."><meta name=keywords content><meta name=robots content="noodp"><link rel=canonical href=https://exception.blog/posts/problemas-com-httpclient-resolvidos/><link rel=stylesheet href=https://exception.blog/assets/style.css><link rel=stylesheet href=https://exception.blog/assets/red.css><link rel=apple-touch-icon href=https://exception.blog/img/apple-touch-icon-192x192.png><link rel="shortcut icon" href=https://exception.blog/favicon.png><meta name=twitter:card content="summary"><meta property="og:locale" content="en"><meta property="og:type" content="article"><meta property="og:title" content="Solucionando problemas de sincronismo de requisições em paralelo com SemaphoreSlim"><meta property="og:description" content="Dando um push() no problema Um dos desafios que nem com as técnicas mais sombrias de debugging me ajudaram a entender o que meu contexto de requisições HTTP assíncronos e paralelos estavam retornando uma exceção baseada no cancelamento das referências das instâncias dos vários CancellationToken utilizados para construir o cliente das requisições.
Foi uma discussão bem legal com alguns monstros da CLR e até mesmo do Roslyn, que com uma paciência de Jó, conseguiram ir a fundo na explicação sobre o funcionamento da pilha de rede dentro do ."><meta property="og:url" content="https://exception.blog/posts/problemas-com-httpclient-resolvidos/"><meta property="og:site_name" content="Jojo's Exceptions"><meta property="og:image" content="https://exception.blog/favicon.png"><meta property="og:image:width" content="2048"><meta property="og:image:height" content="1024"><meta property="article:published_time" content="2020-12-30 18:21:14 -0300 -0300"></head><body class=red><div class="container center headings--one-size"><header class=header><div class=header__inner><div class=header__logo><a href=/><div class=logo>exception</div></a></div><div class=menu-trigger>menu</div></div><nav class=menu><ul class="menu__inner menu__inner--desktop"><li><a href=/about>whois</a></li></ul><ul class="menu__inner menu__inner--mobile"><li><a href=/about>whois</a></li></ul></nav></header><div class=content><div class=post><h1 class=post-title><a href=https://exception.blog/posts/problemas-com-httpclient-resolvidos/>Solucionando problemas de sincronismo de requisições em paralelo com SemaphoreSlim</a></h1><div class=post-meta><span class=post-date>2020-12-30</span>
<span class=post-author>:: jojo</span></div><span class=post-tags>#<a href=https://exception.blog/tags/dotnet/>dotnet</a>&nbsp;
#<a href=https://exception.blog/tags/parallel/>parallel</a>&nbsp;
#<a href=https://exception.blog/tags/async/>async</a>&nbsp;</span><div class=post-content><div><h1 id=dando-um-push-no-problema>Dando um <code>push()</code> no problema<a href=#dando-um-push-no-problema class=hanchor arialabel=Anchor>&#8983;</a></h1><p>Um dos desafios que nem com as técnicas mais sombrias de <em>debugging</em> me ajudaram a entender o que meu contexto de requisições HTTP assíncronos e paralelos estavam retornando uma exceção baseada no cancelamento das referências das instâncias dos vários <code>CancellationToken</code> utilizados para construir o cliente das requisições.</p><p>Foi uma discussão bem legal com alguns monstros da CLR e até mesmo do Roslyn, que com uma paciência de Jó, conseguiram ir a fundo na explicação sobre o funcionamento da pilha de rede dentro do .NET, e também, sobre a abstração que estava consumindo. No geral, as diversas <em>tasks</em> que havia emitido, que foram passadas para serem aguardadas sua execução até o fim como parâmetro da função <code>WhenAll</code> lá do binário <code>System.Runtime.dll</code>.</p><blockquote><p>Para não descer muito o nível, e deixar tudo de maneira bem entendível, não vou abranger muito a explicação que absorvi, e focar na resolução desse problema relativamente simples.</p></blockquote><h1 id=nem-sempre-é-tudo-uma-questão-de-alto-nível>Nem sempre é tudo uma questão de alto nível<a href=#nem-sempre-é-tudo-uma-questão-de-alto-nível class=hanchor arialabel=Anchor>&#8983;</a></h1><p>Em contextos de paralelismo com tarefas que consomem muito tempo do processador, ainda que existem outras várias camadas para orquestrarem essas tarefas, desde de o próprio CPU até o sistema operacional e a própria <em>stack</em> de desenvolvimento, cabe a nós implementarmos controles eficazes na orquestração nas nossas próprias tarefas.</p><p>Especialmente nas linguagens de altíssimo nível, que entregam uma abstração <em>muito abstrata - eu ri por dentro aqui -</em> do que realmente é uma <em>thread</em>, devemos ter essa atenção dobrada para não cair em um contexto de cancelamento pois o tempo de resposta da aplicação para o ambiente onde foi delegada sua execução chegar ao limite.</p><p>Nesse cenário do <code>HttpClientHandler</code> e do <code>HttpClient</code> isso fica mais fácil de se perceber, mesmo que você implemente um <em>timeout</em> na casa dos <code>TimeSpam.FromDays(666)</code>, se o tempo de execução de qualquer uma das funções assíncronas do <code>HttpClient</code>, como a mais utilizada <code>HttpClient.SendAsync(HttpRequestMessage)</code>, podem retornar um <em>timeout</em>, mas não da resposta HTTP do servidor, e sim da sua <code>Task</code> que está no limbo do atual contexto de processamento.</p><blockquote><p>Vai por mim, evite utilizar funções que podem receber uma sobrecarga de uma instância de <code>CancellationToken</code>, se ela pode trabalhar com os <em>status</em> provenientes dessa estrutura, algum motivo tem.</p></blockquote><p>Para simplificar o entendimento de todo esse cenário intangível, vamos trazer ao código uma péssima prática de programação (que quase me fez desistir do desenvolvimento do <a href=https://github.com/BizarreNULL/httpdoom/>HttpDoom</a>) relacionada ao paralelismo e assincronicidade de código:</p><div class=highlight><pre style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-csharp data-lang=csharp><span style=color:#66d9ef>using</span> System;
<span style=color:#66d9ef>using</span> System.Linq;
<span style=color:#66d9ef>using</span> System.Net.Http;
<span style=color:#66d9ef>using</span> System.Threading.Tasks;

<span style=color:#66d9ef>namespace</span> Exception.Examples
{
    <span style=color:#66d9ef>internal</span> <span style=color:#66d9ef>static</span> <span style=color:#66d9ef>class</span> <span style=color:#a6e22e>Program</span>
    {
        <span style=color:#66d9ef>public</span> <span style=color:#66d9ef>static</span> <span style=color:#66d9ef>async</span> Task Main()
        {
             <span style=color:#66d9ef>var</span> tasks = <span style=color:#66d9ef>await</span> Task.WhenAll(Enumerable.Range(<span style=color:#ae81ff>1</span>, <span style=color:#ae81ff>5000</span>)
                 .Select(<span style=color:#ae81ff>_</span> =&gt; <span style=color:#66d9ef>new</span> HttpClient().GetAsync(<span style=color:#e6db74>&#34;https://google.com&#34;</span>)));
             
             tasks
                 .Where(t =&gt; <span style=color:#66d9ef>true</span>)
                 .ToList()
                 .ForEach(r =&gt; Console.WriteLine(<span style=color:#e6db74>$&#34;Google answered {r.StatusCode}&#34;</span>));
        }
    }
}
</code></pre></div><blockquote><p><strong>Nota</strong>: <em>Top-level programs</em> ainda tem algumas coisas bem peculiares para tratar inferência dinâmica de tipos e de contextos assíncronos e paralelos no C# 9, então vamos no clássico <em>entrypoint program</em> mesmo.</p></blockquote><p>Um código bem simples, e que - se liga no <em>plot twist</em> - funciona perfeitamente bem! O motivo de tudo funcionar como deveria, é que temos implementado somente uma única responsabilidade dentro da função paralela e assíncrona, onde é iniciado 5000 <code>Task&lt;HttpResponseMessage></code> que será aguardada logo no seu <em>enclosure</em> que é justamente a própria <code>Task.WhenAll</code>, por ser uma expressão LINQ, o código pode ser um pouco difícil de ler, mas nada que alguns minutos de leitura não resolva.</p><p>O problema que estamos tentando criar, acontece quando além dessa única coisa que é feita (<code>return new HttpClient().GetAsync("https://google.com"))</code>, na expressão anônima da extensão <code>Select()</code> lá do LINQ), adicionamos alguma função que freia a execução dessa <em>thread</em>, por exemplo, escrever na tela informações da requisição conforme são executadas, vamos alterar um pouco o código e adicionar algumas funções que fação operações de IO:</p><div class=highlight><pre style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-csharp data-lang=csharp><span style=color:#75715e>// ...
</span><span style=color:#75715e></span><span style=color:#66d9ef>await</span> Task.WhenAll(Enumerable.Range(<span style=color:#ae81ff>1</span>, <span style=color:#ae81ff>5000</span>)
    .Select(<span style=color:#66d9ef>async</span> <span style=color:#ae81ff>_</span> =&gt;
    {
        <span style=color:#66d9ef>try</span>
        {
            <span style=color:#66d9ef>var</span> response = <span style=color:#66d9ef>await</span> <span style=color:#66d9ef>new</span> HttpClient().GetAsync(<span style=color:#e6db74>&#34;https://google.com&#34;</span>);
            Console.Write(<span style=color:#e6db74>$&#34;Remote {response.RequestMessage?.RequestUri} answered {response.StatusCode}, &#34;</span>);

            <span style=color:#66d9ef>var</span> content = <span style=color:#66d9ef>await</span> response.Content.ReadAsByteArrayAsync();
            Console.WriteLine(<span style=color:#e6db74>$&#34;with a length of {content.Length} byte(s)&#34;</span>);
        
            <span style=color:#66d9ef>return</span> response;
        }
        <span style=color:#66d9ef>catch</span> (System.Exception e)
        {
            Console.WriteLine(e.InnerException != <span style=color:#66d9ef>null</span>
              ? <span style=color:#e6db74>$&#34;Error: {e.InnerException.Message}&#34;</span>
              : <span style=color:#e6db74>$&#34;Error: {e.Message}&#34;</span>);
        }
        
    }));
<span style=color:#75715e>// ...
</span></code></pre></div><p>Nesse cenário como temos a interação com operações que causam problemas na hora de serem executadas, e nem por realizarem operações de IO com <code>response.Content.ReadAsByteArrayAsync()</code> mas sim pela escrita na tela usando <code>System.Console</code>, que causa um <em>lock</em> e vira uma bagunça, quem estiver disponível, executa essa função.</p><p>Quando você executar esse código (além de receber um belíssimo banimento da Google por realizar milhares de requisições em tão pouco tempo), vai se deparar com algumas exceções de <code>Task</code> ao invés das instâncias de classes referentes a pilha de rede do .NET, no caso a famosa mensagem &ldquo;<em>The operation was canceled</em>&rdquo;.</p><p>E justamente quando receber essa resposta, é que os problemas do paralelismo começam a perturbar sua sanidade.</p><h1 id=resolvendo-com-uma-boa-sinalização>Resolvendo com uma boa sinalização<a href=#resolvendo-com-uma-boa-sinalização class=hanchor arialabel=Anchor>&#8983;</a></h1><p>Existem diversas APIs que são fornecidas dentro do CLR para sanar os problemas de paralelismo que correspondem a estes erros, podemos realizar a implementação mais simples que conheço, que tem pouquíssimas alterações no código fonte original da aplicação, utilizando <code>SemaphoreSlim</code> para corrigir esse fiasco.</p><p>Podemos resumir esse elemento de <code>System.Threads</code> como sendo uma entidade responsável por limitar o número de <em>threads</em> que podem acessar uma <em>pool</em> de recursos, que é justamente o que causa &ldquo;<em>The operation was canceled</em>&rdquo; dentro de uma <code>Task</code>. Sua implementação é bem simples, e ele receber por padrão um único argumento correspondente a quantidade máxima de <em>threads</em> que podem ser alocadas para acessar estes recursos:</p><div class=highlight><pre style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-c# data-lang=c#><span style=color:#66d9ef>var</span> semaphore = <span style=color:#66d9ef>new</span> SemaphoreSlim(Environment.ProcessorCount);
<span style=color:#66d9ef>await</span> Task.WhenAll(Enumerable.Range(<span style=color:#ae81ff>1</span>, <span style=color:#ae81ff>1000</span>)
    .Select(<span style=color:#66d9ef>async</span> <span style=color:#ae81ff>_</span> =&gt;
    {
        <span style=color:#66d9ef>await</span> semaphore.WaitAsync();
        <span style=color:#66d9ef>try</span>
        {
            <span style=color:#66d9ef>var</span> response = <span style=color:#66d9ef>await</span> <span style=color:#66d9ef>new</span> HttpClient().GetAsync(<span style=color:#e6db74>&#34;https://zup.com.br&#34;</span>);
            Console.Write(<span style=color:#e6db74>$&#34;Remote {response.RequestMessage?.RequestUri} answered {response.StatusCode}, &#34;</span>);

            <span style=color:#66d9ef>var</span> content = <span style=color:#66d9ef>await</span> response.Content.ReadAsByteArrayAsync();
            Console.WriteLine(<span style=color:#e6db74>$&#34;with a length of {content.Length} byte(s)&#34;</span>);

            <span style=color:#66d9ef>return</span> response;
        }
        <span style=color:#66d9ef>catch</span> (System.Exception e)
        {
            Console.WriteLine(e.InnerException != <span style=color:#66d9ef>null</span>
                ? <span style=color:#e6db74>$&#34;Error: {e.InnerException.Message}&#34;</span>
                : <span style=color:#e6db74>$&#34;Error: {e.Message}&#34;</span>);

            <span style=color:#66d9ef>return</span> <span style=color:#66d9ef>null</span>;
        }
        <span style=color:#66d9ef>finally</span>
        {
            semaphore.Release();
        }
    }));
</code></pre></div><p>Agora além de podermos controlar o número de <em>threads</em> que serão utilizados para realizar as requisições, também não vamos ter problemas de concorrência ao tentar processar essa <em>pool</em> de tarefas alocadas no fluxo de execução da aplicação.</p></div></div><div class=pagination><div class=pagination__title><span class=pagination__title-h>Read other posts</span><hr></div><div class=pagination__buttons><span class="button previous"><a href=https://exception.blog/posts/hackeando-apps-financeiros-para-osint/><span class=button__icon>←</span>
<span class=button__text>Hackeando apps financeiros para OSINT (e pela zueira): Tudo pelo PIX!</span></a></span></div></div></div></div><footer class=footer><div class=footer__inner><div class=copyright><span>© 2021 Powered by <a href=http://gohugo.io>Hugo</a></span>
<span>:: Theme made by <a href=https://twitter.com/panr>panr</a></span></div></div></footer><script src=https://exception.blog/assets/main.js></script><script src=https://exception.blog/assets/prism.js></script></div></body></html>